matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: '10'
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - os: linux
      services: docker
      language: node_js
      node_js: '10'

cache:
  directories:
    - "$HOME/.npm"

install:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      npm ci --ignore-scripts
    else
      npm ci
    fi

script:
  - npm run lint
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        --env-file <(env | grep -vE '\r|\n' | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_') \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "npm run rebuild && npm run build -- --linux --win"
    else
      npm run build -- --mac
    fi
  - sudo rm -rf build/app/{linux-unpacked,mac,win-unpacked,builder-effective-config.yaml}

deploy:
  provider: s3
  access_key_id:
    secure: 5P1pk12LavdIZ1uGUdO0w+dy/Q4wnbg+i8qPD/XrqOvTIBARVeLMTMhxcqWp89dWGAWDxvkutHbwCrEj6uf+N/eKm3Lst8QDF//xicaiEU9I4LAkiQ82M3chw+9ebEtW0VALpLZWNIjzRE17YludSeTTuFFZgcPILo5KfqqFHehsLPqx84FVAbP5eJ5kiM3u5QunX5Lg+r9dtVaPU/TN5c6Q5+yuAJupRwveW6mmnB3AaPlpgGvAB/sZiy1YaJ3nmHUEubuQEpKCcld1kjgE+cESME0VVJ94peYwYQDWYaEKd360OyGOXeJMAdXKvh8oVVbwJUfy5eezRtPkmu3gU0Hbcqw+04zxE7JpkQcDzwrgqkVjichEaHaBVkHMfCWsunkCAyAilol1tqVk7M9snewT19CJ3mHaeMK0y5RLb/ESt6YRmNH4/bFeSsg+Ppx3CXpIWl1Qh6qxV27IwMD8QXPGW3lvMTfPnZsxUrXzdTscVZANbzVNW8tHXS3KaIBsKX3ASVcZOiBCF2BLuLtbCU92JoPjTOaYbD62TtwtMNz613G2DzbaZx4HrSNRe8aN4vRLKOGZa9kHMinSwSGERYJIjRfZ1CM7+a8bbCUliCn+VgjKYgBu3uUclDYyvGvWpas6sMceD/8uFauY4C8as7TJQDDU0EhARxiOpsTFbsk=
  secret_access_key:
    secure: wMGkQLXOn0bBdBWR03om1gsPF4dEjHHYWqMtowGnBJd0IoHbuvMN1zKgLVreVBMcJxarAl2FFIB74073SpSf7cwUn4F7fzHMOr1bigsUK/kwn5J1NFRXnjoz6I78YI1IJEPwSNNr5ZEjVJtnq/NElXuwQdbXm9oRYF9U7WdwVt+P9XQY8dpGtGeyMLJT8zQN9iD8l7IRHU1jHgu+3cJTEn6VvDKCF+Emf0JOBd2kIAknBzqNhgeaUHMjM190etjZAQu0TtBOnvMF8+RqzIBpJm7ICVBatg231mh5ehHd6OwayddBipNao+NtRBsaW/zVhRWvwbaVe8K/avxccaOKRXIWmUDzpoMD+p+XFdr3J/ncrS40+k1KigkFX8foVHZUHh/uOrrK1krsApTVmzvV8Dt07LiUCaILMYE0OUIqgwSG+3e+2taGBHJECw8RmlTNoqjxl9QVZofUf/Dhq3hor52RMh27sliNSFEC1U1qYus7FwiqV/hG1i3s8kMtdRf/Oxb16N9sjs5uZBJJCoDTGgpZdChs4ldeRBtgizPruCfIMtVb4mU6kVC3FY+45yngkUWh7lDg6hzJ9MISJX6s6jyqHbqoAogLqqW1R4lhciwxQHMTb4tZ/UypIS50cwoHYa94uOqq12yQ2qnnBwE7tJw/4OCULjfxnSooxiCypFw=
  bucket: family-photos-app
  region: eu-central-1
  local_dir: build/app
  upload-dir: $TRAVIS_BRANCH
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^develop|master$
